create table public.comment_table (id int8 not null, text varchar(255) not null, author_id int8, post_id int8, primary key (id));
create table public.label_table (id int8 not null, label_name varchar(255), primary key (id));
create table public.post_table (id int8 not null, url varchar(255), description varchar(1000), uuid uuid, author_id int8, primary key (id));
create table public.role_table (id int8 not null, name varchar(50) not null, primary key (id));
create table public.user_table (id int8 not null, email varchar(255), first_name varchar(50), last_name varchar(50), password_hash varchar(60) not null, profile_photo_url varchar(255), username varchar(50), uuid uuid, role_id int8, primary key (id));
alter table if exists public.label_table add constraint UK_6oepxgeoxdgqxdnbe9k3v0dwx unique (label_name);
alter table if exists public.post_table add constraint UK_eqm1l2f7m2dtjslgrei31esbr unique (uuid);
alter table if exists public.role_table add constraint UK_6cf7j1mnc67sslb6fec3m3wsh unique (name);
alter table if exists public.user_table add constraint UK_eamk4l51hm6yqb8xw37i23kb5 unique (email);
alter table if exists public.user_table add constraint UK_as85vd3tv1f8ljew12glptgpc unique (uuid);
create sequence hibernate_sequence start 1 increment 1;
create table public.post_table_labels (post_id int8 not null, labels_id int8 not null, primary key (post_id, labels_id));
create table public.user_table_following (followed_by_id int8 not null, following_id int8 not null, primary key (followed_by_id, following_id));
alter table if exists public.comment_table add constraint FK3n0lcjw815g5ibu5fwh9o92p0 foreign key (author_id) references public.user_table;
alter table if exists public.comment_table add constraint FKjftvy6rlb867yye3dx0vbirfg foreign key (post_id) references public.post_table;
alter table if exists public.post_table add constraint FKpv7ojbodgytp201q2jb8wv4fp foreign key (author_id) references public.user_table;
alter table if exists public.user_table add constraint FK2khye3lldnmbjjkfdug9k3fp4 foreign key (role_id) references public.role_table;
alter table if exists public.post_table_labels add constraint FKjg79mh76cl23l1vkjeuib5k4 foreign key (labels_id) references public.label_table;
alter table if exists public.post_table_labels add constraint FKbox0s0uykprqeq9epsuwf9xkh foreign key (post_id) references public.post_table;
alter table if exists public.user_table_following add constraint FKc6t4vx0w9n6wkrx9n5un7gq9y foreign key (following_id) references public.user_table;
alter table if exists public.user_table_following add constraint FKhx7qrqu51ja7s6eytqbt90bt6 foreign key (followed_by_id) references public.user_table;
