create sequence hibernate_sequence start 1;
create table comment (id int8 not null, text varchar(255) not null, author_id int8, post_id int8, primary key (id));
create table label (id int8 not null, label_name varchar(255), primary key (id));
create table post (id int8 not null, url varchar(255), description varchar(1000), uuid uuid, author_id int8, primary key (id));
create table post_labels (post_id int8 not null, labels_id int8 not null, primary key (post_id, labels_id));
create table role (id int8 not null, name varchar(50) not null, primary key (id));
create table "user" (id int8 not null, email varchar(255), first_name varchar(50), last_name varchar(50), password_hash varchar(60) not null, profile_photo_url varchar(255), username varchar(50), uuid uuid, role_id int8, primary key (id));
create table user_following (followed_by_id int8 not null, following_id int8 not null, primary key (followed_by_id, following_id));
alter table if exists label add constraint UK_n8anthjtjgpj83i8mwwslvg9e unique (label_name);
alter table if exists post add constraint UK_b1a5vs6t5vi32stck5kjw0tgf unique (uuid);
alter table if exists role add constraint UK_epk9im9l9q67xmwi4hbed25do unique (name);
alter table if exists "user" add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email);
alter table if exists "user" add constraint UK_1xc1iry6gqjrvh5cpajiq7l2f unique (uuid);
alter table if exists comment add constraint FKh1gtv412u19wcbx22177xbkjp foreign key (author_id) references "user";
alter table if exists comment add constraint FKs1slvnkuemjsq2kj4h3vhx7i1 foreign key (post_id) references post;
alter table if exists post add constraint FK12njtf8e0jmyb45lqfpt6ad89 foreign key (author_id) references "user";
alter table if exists post_labels add constraint FK57l0pexu6mx40ehxiq17oxxu9 foreign key (labels_id) references label;
alter table if exists post_labels add constraint FKjj16h83j6ke5vljjlv26driyr foreign key (post_id) references post;
alter table if exists "user" add constraint FKn82ha3ccdebhokx3a8fgdqeyy foreign key (role_id) references role;
alter table if exists user_following add constraint FKj0avh5q4feap4g0rkus640u4d foreign key (following_id) references "user";
alter table if exists user_following add constraint FKd0h824ogn0dprqrxbkhvowiee foreign key (followed_by_id) references "user";
