security:
  authorizationHeaderName: Authorization
  authoritiesKey: auth
  token:
    prefix: Bearer
    validityInSeconds: 864000
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true